// Bundles @statuscraft/core into the mod, because a hooks module can import only its own
// files (by relative path) and "claude-code": no npm packages. The CLI build calls this too.
import * as fs from 'node:fs';
import * as path from 'node:path';

const pluginRoot = path.resolve(import.meta.dir, '..');
const entry = path.resolve(pluginRoot, '../core/src/index.ts');
const outfile = path.join(pluginRoot, 'hooks', 'vendor', 'core.js');

const result = await Bun.build({
  entrypoints: [entry],
  target: 'browser',
  format: 'esm',
  minify: true,
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error('Failed to bundle @statuscraft/core for the plugin');
}

const code = await result.outputs[0]!.text();
// The mod's loader refuses these, so fail the build rather than ship a mod that does not load
for (const [pattern, why] of [
  [/\brequire\(/, 'require()'],
  [/\bimport\(/, 'a dynamic import()'],
  [/\x1b/, 'a raw escape character (write "\\x1b" in source instead)'],
] as const) {
  if (pattern.test(code)) throw new Error(`vendor/core.js contains ${why}`);
}

fs.mkdirSync(path.dirname(outfile), { recursive: true });
fs.writeFileSync(outfile, `// Generated by packages/plugin/scripts/build.ts from packages/core. Do not edit.\n/* eslint-disable */\n${code}`);
// Types for editors: the real ones, from the core sources (never loaded at run time)
fs.writeFileSync(
  path.join(path.dirname(outfile), 'core.d.ts'),
  "// Generated by packages/plugin/scripts/build.ts. Do not edit.\nexport * from '../../../core/src/index';\n",
);
console.log(`  hooks/vendor/core.js ${(fs.statSync(outfile).size / 1024).toFixed(1)} KB`);

// /statuscraft setup and doctor run exactly the CLI release this mod was built with, never a newer untested one
const cliVersion = JSON.parse(fs.readFileSync(path.resolve(pluginRoot, '../cli/package.json'), 'utf8')).version as string;
fs.writeFileSync(
  path.join(path.dirname(outfile), 'version.js'),
  `// Generated by packages/plugin/scripts/build.ts from packages/cli/package.json. Do not edit.\nexport const CLI_VERSION = '${cliVersion}'\n`,
);
fs.writeFileSync(
  path.join(path.dirname(outfile), 'version.d.ts'),
  '// Generated by packages/plugin/scripts/build.ts. Do not edit.\nexport declare const CLI_VERSION: string\n',
);
