
export interface AnsiColors {
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
  background: string;
  foreground: string;
}

export interface TerminalTheme {
  name: string;
  colors: AnsiColors;
}

export interface Terminal {
  name: string;
  icon?: string;
  themes: Record<string, TerminalTheme>;
  defaultTheme: string;
}

export const terminals: Record<string, Terminal> = {
  'iterm2': {
    name: 'iTerm2',
    defaultTheme: 'default',
    themes: {
      'default': {
        name: 'Default',
        colors: {
          background: '#000000',
          foreground: '#c7c7c7',
          black: '#000000',
          red: '#c91b00',
          green: '#00c200',
          yellow: '#c7c400',
          blue: '#0225c7',
          magenta: '#c930c7',
          cyan: '#00c5c7',
          white: '#c7c7c7',
          brightBlack: '#676767',
          brightRed: '#ff6d67',
          brightGreen: '#5ff967',
          brightYellow: '#fefb67',
          brightBlue: '#6871ff',
          brightMagenta: '#ff76ff',
          brightCyan: '#5ffdff',
          brightWhite: '#feffff',
        },
      },
      'dracula': {
        name: 'Dracula',
        colors: {
          background: '#282a36',
          foreground: '#f8f8f2',
          black: '#21222c',
          red: '#ff5555',
          green: '#50fa7b',
          yellow: '#f1fa8c',
          blue: '#bd93f9',
          magenta: '#ff79c6',
          cyan: '#8be9fd',
          white: '#f8f8f2',
          brightBlack: '#6272a4',
          brightRed: '#ff6e6e',
          brightGreen: '#69ff94',
          brightYellow: '#ffffa5',
          brightBlue: '#d6acff',
          brightMagenta: '#ff92df',
          brightCyan: '#a4ffff',
          brightWhite: '#ffffff',
        },
      },
      'one-dark': {
        name: 'One Dark',
        colors: {
          background: '#282c34',
          foreground: '#abb2bf',
          black: '#282c34',
          red: '#e06c75',
          green: '#98c379',
          yellow: '#e5c07b',
          blue: '#61afef',
          magenta: '#c678dd',
          cyan: '#56b6c2',
          white: '#abb2bf',
          brightBlack: '#5c6370',
          brightRed: '#e06c75',
          brightGreen: '#98c379',
          brightYellow: '#e5c07b',
          brightBlue: '#61afef',
          brightMagenta: '#c678dd',
          brightCyan: '#56b6c2',
          brightWhite: '#ffffff',
        },
      },
      'solarized-dark': {
        name: 'Solarized Dark',
        colors: {
          background: '#002b36',
          foreground: '#839496',
          black: '#073642',
          red: '#dc322f',
          green: '#859900',
          yellow: '#b58900',
          blue: '#268bd2',
          magenta: '#d33682',
          cyan: '#2aa198',
          white: '#eee8d5',
          brightBlack: '#002b36',
          brightRed: '#cb4b16',
          brightGreen: '#586e75',
          brightYellow: '#657b83',
          brightBlue: '#839496',
          brightMagenta: '#6c71c4',
          brightCyan: '#93a1a1',
          brightWhite: '#fdf6e3',
        },
      },
      'nord': {
        name: 'Nord',
        colors: {
          background: '#2e3440',
          foreground: '#d8dee9',
          black: '#3b4252',
          red: '#bf616a',
          green: '#a3be8c',
          yellow: '#ebcb8b',
          blue: '#81a1c1',
          magenta: '#b48ead',
          cyan: '#88c0d0',
          white: '#e5e9f0',
          brightBlack: '#4c566a',
          brightRed: '#bf616a',
          brightGreen: '#a3be8c',
          brightYellow: '#ebcb8b',
          brightBlue: '#81a1c1',
          brightMagenta: '#b48ead',
          brightCyan: '#8fbcbb',
          brightWhite: '#eceff4',
        },
      },
      'catppuccin-mocha': {
        name: 'Catppuccin Mocha',
        colors: {
          background: '#1e1e2e',
          foreground: '#cdd6f4',
          black: '#45475a',
          red: '#f38ba8',
          green: '#a6e3a1',
          yellow: '#f9e2af',
          blue: '#89b4fa',
          magenta: '#f5c2e7',
          cyan: '#94e2d5',
          white: '#bac2de',
          brightBlack: '#585b70',
          brightRed: '#f38ba8',
          brightGreen: '#a6e3a1',
          brightYellow: '#f9e2af',
          brightBlue: '#89b4fa',
          brightMagenta: '#f5c2e7',
          brightCyan: '#94e2d5',
          brightWhite: '#a6adc8',
        },
      },
      'tokyo-night': {
        name: 'Tokyo Night',
        colors: {
          background: '#1a1b26',
          foreground: '#c0caf5',
          black: '#15161e',
          red: '#f7768e',
          green: '#9ece6a',
          yellow: '#e0af68',
          blue: '#7aa2f7',
          magenta: '#bb9af7',
          cyan: '#7dcfff',
          white: '#a9b1d6',
          brightBlack: '#414868',
          brightRed: '#f7768e',
          brightGreen: '#9ece6a',
          brightYellow: '#e0af68',
          brightBlue: '#7aa2f7',
          brightMagenta: '#bb9af7',
          brightCyan: '#7dcfff',
          brightWhite: '#c0caf5',
        },
      },
      'gruvbox-dark': {
        name: 'Gruvbox Dark',
        colors: {
          background: '#282828',
          foreground: '#ebdbb2',
          black: '#282828',
          red: '#cc241d',
          green: '#98971a',
          yellow: '#d79921',
          blue: '#458588',
          magenta: '#b16286',
          cyan: '#689d6a',
          white: '#a89984',
          brightBlack: '#928374',
          brightRed: '#fb4934',
          brightGreen: '#b8bb26',
          brightYellow: '#fabd2f',
          brightBlue: '#83a598',
          brightMagenta: '#d3869b',
          brightCyan: '#8ec07c',
          brightWhite: '#ebdbb2',
        },
      },
    },
  },

  'windows-terminal': {
    name: 'Windows Terminal',
    defaultTheme: 'campbell',
    themes: {
      'campbell': {
        name: 'Campbell',
        colors: {
          background: '#0c0c0c',
          foreground: '#cccccc',
          black: '#0c0c0c',
          red: '#c50f1f',
          green: '#13a10e',
          yellow: '#c19c00',
          blue: '#0037da',
          magenta: '#881798',
          cyan: '#3a96dd',
          white: '#cccccc',
          brightBlack: '#767676',
          brightRed: '#e74856',
          brightGreen: '#16c60c',
          brightYellow: '#f9f1a5',
          brightBlue: '#3b78ff',
          brightMagenta: '#b4009e',
          brightCyan: '#61d6d6',
          brightWhite: '#f2f2f2',
        },
      },
      'one-half-dark': {
        name: 'One Half Dark',
        colors: {
          background: '#282c34',
          foreground: '#dcdfe4',
          black: '#282c34',
          red: '#e06c75',
          green: '#98c379',
          yellow: '#e5c07b',
          blue: '#61afef',
          magenta: '#c678dd',
          cyan: '#56b6c2',
          white: '#dcdfe4',
          brightBlack: '#5a6374',
          brightRed: '#e06c75',
          brightGreen: '#98c379',
          brightYellow: '#e5c07b',
          brightBlue: '#61afef',
          brightMagenta: '#c678dd',
          brightCyan: '#56b6c2',
          brightWhite: '#dcdfe4',
        },
      },
      'tango-dark': {
        name: 'Tango Dark',
        colors: {
          background: '#000000',
          foreground: '#d3d7cf',
          black: '#000000',
          red: '#cc0000',
          green: '#4e9a06',
          yellow: '#c4a000',
          blue: '#3465a4',
          magenta: '#75507b',
          cyan: '#06989a',
          white: '#d3d7cf',
          brightBlack: '#555753',
          brightRed: '#ef2929',
          brightGreen: '#8ae234',
          brightYellow: '#fce94f',
          brightBlue: '#729fcf',
          brightMagenta: '#ad7fa8',
          brightCyan: '#34e2e2',
          brightWhite: '#eeeeec',
        },
      },
      'dracula': {
        name: 'Dracula',
        colors: {
          background: '#282a36',
          foreground: '#f8f8f2',
          black: '#21222c',
          red: '#ff5555',
          green: '#50fa7b',
          yellow: '#f1fa8c',
          blue: '#bd93f9',
          magenta: '#ff79c6',
          cyan: '#8be9fd',
          white: '#f8f8f2',
          brightBlack: '#6272a4',
          brightRed: '#ff6e6e',
          brightGreen: '#69ff94',
          brightYellow: '#ffffa5',
          brightBlue: '#d6acff',
          brightMagenta: '#ff92df',
          brightCyan: '#a4ffff',
          brightWhite: '#ffffff',
        },
      },
    },
  },

  'vscode': {
    name: 'VS Code Terminal',
    defaultTheme: 'dark-modern',
    themes: {
      'dark-modern': {
        name: 'Dark Modern',
        colors: {
          background: '#1f1f1f',
          foreground: '#cccccc',
          black: '#1f1f1f',
          red: '#f14c4c',
          green: '#23d18b',
          yellow: '#f5f543',
          blue: '#3b8eea',
          magenta: '#d670d6',
          cyan: '#29b8db',
          white: '#cccccc',
          brightBlack: '#5a5a5a',
          brightRed: '#f14c4c',
          brightGreen: '#23d18b',
          brightYellow: '#f5f543',
          brightBlue: '#3b8eea',
          brightMagenta: '#d670d6',
          brightCyan: '#29b8db',
          brightWhite: '#ffffff',
        },
      },
      'dark-plus': {
        name: 'Dark+',
        colors: {
          background: '#1e1e1e',
          foreground: '#d4d4d4',
          black: '#000000',
          red: '#cd3131',
          green: '#0dbc79',
          yellow: '#e5e510',
          blue: '#2472c8',
          magenta: '#bc3fbc',
          cyan: '#11a8cd',
          white: '#e5e5e5',
          brightBlack: '#666666',
          brightRed: '#f14c4c',
          brightGreen: '#23d18b',
          brightYellow: '#f5f543',
          brightBlue: '#3b8eea',
          brightMagenta: '#d670d6',
          brightCyan: '#29b8db',
          brightWhite: '#ffffff',
        },
      },
      'monokai': {
        name: 'Monokai',
        colors: {
          background: '#272822',
          foreground: '#f8f8f2',
          black: '#272822',
          red: '#f92672',
          green: '#a6e22e',
          yellow: '#f4bf75',
          blue: '#66d9ef',
          magenta: '#ae81ff',
          cyan: '#a1efe4',
          white: '#f8f8f2',
          brightBlack: '#75715e',
          brightRed: '#f92672',
          brightGreen: '#a6e22e',
          brightYellow: '#f4bf75',
          brightBlue: '#66d9ef',
          brightMagenta: '#ae81ff',
          brightCyan: '#a1efe4',
          brightWhite: '#f9f8f5',
        },
      },
    },
  },

  'alacritty': {
    name: 'Alacritty',
    defaultTheme: 'default',
    themes: {
      'default': {
        name: 'Default',
        colors: {
          background: '#1d1f21',
          foreground: '#c5c8c6',
          black: '#1d1f21',
          red: '#cc6666',
          green: '#b5bd68',
          yellow: '#f0c674',
          blue: '#81a2be',
          magenta: '#b294bb',
          cyan: '#8abeb7',
          white: '#c5c8c6',
          brightBlack: '#969896',
          brightRed: '#cc6666',
          brightGreen: '#b5bd68',
          brightYellow: '#f0c674',
          brightBlue: '#81a2be',
          brightMagenta: '#b294bb',
          brightCyan: '#8abeb7',
          brightWhite: '#ffffff',
        },
      },
      'dracula': {
        name: 'Dracula',
        colors: {
          background: '#282a36',
          foreground: '#f8f8f2',
          black: '#21222c',
          red: '#ff5555',
          green: '#50fa7b',
          yellow: '#f1fa8c',
          blue: '#bd93f9',
          magenta: '#ff79c6',
          cyan: '#8be9fd',
          white: '#f8f8f2',
          brightBlack: '#6272a4',
          brightRed: '#ff6e6e',
          brightGreen: '#69ff94',
          brightYellow: '#ffffa5',
          brightBlue: '#d6acff',
          brightMagenta: '#ff92df',
          brightCyan: '#a4ffff',
          brightWhite: '#ffffff',
        },
      },
      'nord': {
        name: 'Nord',
        colors: {
          background: '#2e3440',
          foreground: '#d8dee9',
          black: '#3b4252',
          red: '#bf616a',
          green: '#a3be8c',
          yellow: '#ebcb8b',
          blue: '#81a1c1',
          magenta: '#b48ead',
          cyan: '#88c0d0',
          white: '#e5e9f0',
          brightBlack: '#4c566a',
          brightRed: '#bf616a',
          brightGreen: '#a3be8c',
          brightYellow: '#ebcb8b',
          brightBlue: '#81a1c1',
          brightMagenta: '#b48ead',
          brightCyan: '#8fbcbb',
          brightWhite: '#eceff4',
        },
      },
      'gruvbox-dark': {
        name: 'Gruvbox Dark',
        colors: {
          background: '#282828',
          foreground: '#ebdbb2',
          black: '#282828',
          red: '#cc241d',
          green: '#98971a',
          yellow: '#d79921',
          blue: '#458588',
          magenta: '#b16286',
          cyan: '#689d6a',
          white: '#a89984',
          brightBlack: '#928374',
          brightRed: '#fb4934',
          brightGreen: '#b8bb26',
          brightYellow: '#fabd2f',
          brightBlue: '#83a598',
          brightMagenta: '#d3869b',
          brightCyan: '#8ec07c',
          brightWhite: '#ebdbb2',
        },
      },
    },
  },

  'kitty': {
    name: 'Kitty',
    defaultTheme: 'default',
    themes: {
      'default': {
        name: 'Default',
        colors: {
          background: '#000000',
          foreground: '#dddddd',
          black: '#000000',
          red: '#cc0403',
          green: '#19cb00',
          yellow: '#cecb00',
          blue: '#0d73cc',
          magenta: '#cb1ed1',
          cyan: '#0dcdcd',
          white: '#dddddd',
          brightBlack: '#767676',
          brightRed: '#f2201f',
          brightGreen: '#23fd00',
          brightYellow: '#fffd00',
          brightBlue: '#1a8fff',
          brightMagenta: '#fd28ff',
          brightCyan: '#14ffff',
          brightWhite: '#ffffff',
        },
      },
      'catppuccin-mocha': {
        name: 'Catppuccin Mocha',
        colors: {
          background: '#1e1e2e',
          foreground: '#cdd6f4',
          black: '#45475a',
          red: '#f38ba8',
          green: '#a6e3a1',
          yellow: '#f9e2af',
          blue: '#89b4fa',
          magenta: '#f5c2e7',
          cyan: '#94e2d5',
          white: '#bac2de',
          brightBlack: '#585b70',
          brightRed: '#f38ba8',
          brightGreen: '#a6e3a1',
          brightYellow: '#f9e2af',
          brightBlue: '#89b4fa',
          brightMagenta: '#f5c2e7',
          brightCyan: '#94e2d5',
          brightWhite: '#a6adc8',
        },
      },
      'tokyo-night': {
        name: 'Tokyo Night',
        colors: {
          background: '#1a1b26',
          foreground: '#c0caf5',
          black: '#15161e',
          red: '#f7768e',
          green: '#9ece6a',
          yellow: '#e0af68',
          blue: '#7aa2f7',
          magenta: '#bb9af7',
          cyan: '#7dcfff',
          white: '#a9b1d6',
          brightBlack: '#414868',
          brightRed: '#f7768e',
          brightGreen: '#9ece6a',
          brightYellow: '#e0af68',
          brightBlue: '#7aa2f7',
          brightMagenta: '#bb9af7',
          brightCyan: '#7dcfff',
          brightWhite: '#c0caf5',
        },
      },
    },
  },

  'warp': {
    name: 'Warp',
    defaultTheme: 'default',
    themes: {
      'default': {
        name: 'Default Dark',
        colors: {
          background: '#1e1e28',
          foreground: '#e4e4e8',
          black: '#1e1e28',
          red: '#e55c5c',
          green: '#6ec05c',
          yellow: '#eab766',
          blue: '#5c8de5',
          magenta: '#c05cbe',
          cyan: '#5cbeaa',
          white: '#e4e4e8',
          brightBlack: '#54546c',
          brightRed: '#f07178',
          brightGreen: '#bae67e',
          brightYellow: '#ffd580',
          brightBlue: '#73d0ff',
          brightMagenta: '#d4bfff',
          brightCyan: '#95e6cb',
          brightWhite: '#ffffff',
        },
      },
      'dracula': {
        name: 'Dracula',
        colors: {
          background: '#282a36',
          foreground: '#f8f8f2',
          black: '#21222c',
          red: '#ff5555',
          green: '#50fa7b',
          yellow: '#f1fa8c',
          blue: '#bd93f9',
          magenta: '#ff79c6',
          cyan: '#8be9fd',
          white: '#f8f8f2',
          brightBlack: '#6272a4',
          brightRed: '#ff6e6e',
          brightGreen: '#69ff94',
          brightYellow: '#ffffa5',
          brightBlue: '#d6acff',
          brightMagenta: '#ff92df',
          brightCyan: '#a4ffff',
          brightWhite: '#ffffff',
        },
      },
    },
  },

  'ghostty': {
    name: 'Ghostty',
    defaultTheme: 'default',
    themes: {
      'default': {
        name: 'Default',
        colors: {
          background: '#282c34',
          foreground: '#ffffff',
          black: '#1d2021',
          red: '#cc241d',
          green: '#98971a',
          yellow: '#d79921',
          blue: '#458588',
          magenta: '#b16286',
          cyan: '#689d6a',
          white: '#a89984',
          brightBlack: '#928374',
          brightRed: '#fb4934',
          brightGreen: '#b8bb26',
          brightYellow: '#fabd2f',
          brightBlue: '#83a598',
          brightMagenta: '#d3869b',
          brightCyan: '#8ec07c',
          brightWhite: '#ebdbb2',
        },
      },
      'catppuccin-mocha': {
        name: 'Catppuccin Mocha',
        colors: {
          background: '#1e1e2e',
          foreground: '#cdd6f4',
          black: '#45475a',
          red: '#f38ba8',
          green: '#a6e3a1',
          yellow: '#f9e2af',
          blue: '#89b4fa',
          magenta: '#f5c2e7',
          cyan: '#94e2d5',
          white: '#bac2de',
          brightBlack: '#585b70',
          brightRed: '#f38ba8',
          brightGreen: '#a6e3a1',
          brightYellow: '#f9e2af',
          brightBlue: '#89b4fa',
          brightMagenta: '#f5c2e7',
          brightCyan: '#94e2d5',
          brightWhite: '#a6adc8',
        },
      },
    },
  },

  'macos-terminal': {
    name: 'macOS Terminal',
    defaultTheme: 'basic',
    themes: {
      'basic': {
        name: 'Basic',
        colors: {
          background: '#ffffff',
          foreground: '#000000',
          black: '#000000',
          red: '#990000',
          green: '#00a600',
          yellow: '#999900',
          blue: '#0000b2',
          magenta: '#b200b2',
          cyan: '#00a6b2',
          white: '#bfbfbf',
          brightBlack: '#666666',
          brightRed: '#e50000',
          brightGreen: '#00d900',
          brightYellow: '#e5e500',
          brightBlue: '#0000ff',
          brightMagenta: '#e500e5',
          brightCyan: '#00e5e5',
          brightWhite: '#e5e5e5',
        },
      },
      'pro': {
        name: 'Pro',
        colors: {
          background: '#000000',
          foreground: '#f2f2f2',
          black: '#000000',
          red: '#990000',
          green: '#00a600',
          yellow: '#999900',
          blue: '#1f08db',
          magenta: '#b200b2',
          cyan: '#00a6b2',
          white: '#bfbfbf',
          brightBlack: '#666666',
          brightRed: '#e50000',
          brightGreen: '#00d900',
          brightYellow: '#e5e500',
          brightBlue: '#0000ff',
          brightMagenta: '#e500e5',
          brightCyan: '#00e5e5',
          brightWhite: '#e5e5e5',
        },
      },
    },
  },

  'gnome-terminal': {
    name: 'GNOME Terminal',
    defaultTheme: 'tango',
    themes: {
      'tango': {
        name: 'Tango',
        colors: {
          background: '#2e3436',
          foreground: '#d3d7cf',
          black: '#2e3436',
          red: '#cc0000',
          green: '#4e9a06',
          yellow: '#c4a000',
          blue: '#3465a4',
          magenta: '#75507b',
          cyan: '#06989a',
          white: '#d3d7cf',
          brightBlack: '#555753',
          brightRed: '#ef2929',
          brightGreen: '#8ae234',
          brightYellow: '#fce94f',
          brightBlue: '#729fcf',
          brightMagenta: '#ad7fa8',
          brightCyan: '#34e2e2',
          brightWhite: '#eeeeec',
        },
      },
      'solarized-dark': {
        name: 'Solarized Dark',
        colors: {
          background: '#002b36',
          foreground: '#839496',
          black: '#073642',
          red: '#dc322f',
          green: '#859900',
          yellow: '#b58900',
          blue: '#268bd2',
          magenta: '#d33682',
          cyan: '#2aa198',
          white: '#eee8d5',
          brightBlack: '#002b36',
          brightRed: '#cb4b16',
          brightGreen: '#586e75',
          brightYellow: '#657b83',
          brightBlue: '#839496',
          brightMagenta: '#6c71c4',
          brightCyan: '#93a1a1',
          brightWhite: '#fdf6e3',
        },
      },
    },
  },

  'hyper': {
    name: 'Hyper',
    defaultTheme: 'default',
    themes: {
      'default': {
        name: 'Default',
        colors: {
          background: '#000000',
          foreground: '#ffffff',
          black: '#000000',
          red: '#ff0000',
          green: '#33ff00',
          yellow: '#ffff00',
          blue: '#0066ff',
          magenta: '#cc00ff',
          cyan: '#00ffff',
          white: '#d0d0d0',
          brightBlack: '#808080',
          brightRed: '#ff0000',
          brightGreen: '#33ff00',
          brightYellow: '#ffff00',
          brightBlue: '#0066ff',
          brightMagenta: '#cc00ff',
          brightCyan: '#00ffff',
          brightWhite: '#ffffff',
        },
      },
      'hyper-snazzy': {
        name: 'Hyper Snazzy',
        colors: {
          background: '#282a36',
          foreground: '#eff0eb',
          black: '#282a36',
          red: '#ff5c57',
          green: '#5af78e',
          yellow: '#f3f99d',
          blue: '#57c7ff',
          magenta: '#ff6ac1',
          cyan: '#9aedfe',
          white: '#f1f1f0',
          brightBlack: '#686868',
          brightRed: '#ff5c57',
          brightGreen: '#5af78e',
          brightYellow: '#f3f99d',
          brightBlue: '#57c7ff',
          brightMagenta: '#ff6ac1',
          brightCyan: '#9aedfe',
          brightWhite: '#f1f1f0',
        },
      },
    },
  },
};
