import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  createScenarioContext,
  PRESETS,
  renderStatusText,
  renderWidget,
  stripAnsi,
  WIDGET_CATEGORIES,
  WIDGETS,
} from '../packages/core/src/index.ts';

const root = path.resolve(import.meta.dir, '..');
const now = Date.UTC(2026, 9, 5, 14, 30);
const busy = createScenarioContext('busy', { now });
const escape = (text: string) => text.replace(/\|/g, '\\|');

const widgetLines = [
  '# Widgets',
  '',
  '<!-- Generated by `bun run docs` from packages/core/src/widgets/catalog. Do not edit by hand. -->',
  '',
  `StatusCraft has ${WIDGETS.length} bricks. Examples show a busy session.`,
  '',
];
for (const category of WIDGET_CATEGORIES) {
  const widgets = WIDGETS.filter((w) => w.category === category.id);
  widgetLines.push(`## ${category.emoji} ${category.name}`, '', '| Brick | Type | Example | What it shows |', '| --- | --- | --- | --- |');
  for (const widget of widgets) {
    const sample = renderWidget({ id: 'docs', type: widget.type, commandPath: 'date +%H:%M', customText: '🚀 ship it' }, busy);
    const notes = [
      widget.thresholds ? 'warning colors' : '',
      widget.needs?.includes('companion') ? 'needs the plugin' : '',
      widget.options?.length ? `options: ${widget.options.map((o) => o.key).join(', ')}` : '',
    ].filter(Boolean);
    widgetLines.push(
      `| ${widget.emoji} ${widget.name} | \`${widget.type}\` | ${sample ? '`' + escape(stripAnsi(sample)) + '`' : '(hidden)'} | ${escape(widget.description)}${notes.length ? ` (${notes.join('; ')})` : ''} |`,
    );
  }
  widgetLines.push('');
}
fs.writeFileSync(path.join(root, 'docs/widgets.md'), widgetLines.join('\n'));

const presetLines = [
  '# Starter kits',
  '',
  '<!-- Generated by `bun run docs` from packages/core/src/config/presets.ts. Do not edit by hand. -->',
  '',
  'Use one with `npx statuscraft apply <id>`, or pick it in the editor.',
  '',
];
for (const preset of PRESETS) {
  presetLines.push(
    `## ${preset.emoji} ${preset.name} (\`${preset.id}\`)`,
    '',
    preset.description + (preset.needsNerdFont ? ' Needs a [Nerd Font](https://www.nerdfonts.com).' : ''),
    '',
    '```',
    stripAnsi(renderStatusText(preset.layout, createScenarioContext('busy', { now, terminalWidth: 120 }))),
    '```',
    '',
  );
}
fs.writeFileSync(path.join(root, 'docs/presets.md'), presetLines.join('\n'));
console.log(`Wrote docs/widgets.md (${WIDGETS.length} widgets) and docs/presets.md (${PRESETS.length} presets)`);
